[platformio]
src_dir = .

[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<*.c> +<*.cpp> -<SIMA2.c> -<motor_test.cpp>
build_flags = -I.

[env:motor_test]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<motor_test.cpp>
build_flags = -I.
