[platformio]
src_dir = .

[env:sima_beta]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<src/main.cpp>
build_flags = -I.

[env:servo_test]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
build_src_filter = +<servo_test.cpp>
build_flags = -I.


